import type { Metadata } from "next";
import Login from "./_components/Login";
import Provider from "./_components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Login />
          {children}
        </Provider>
      </body>
    </html>
  );
}
